###Listar todas las personas
GET http://localhost:3000/api/personas

###Obtener una persona por DNI
GET http://localhost:3000/api/personas/12345678

###Registrar un veterinario
POST http://localhost:3000/api/personas
Content-Type: application/json

{
    "dni": 35581075,
    "nombre": "Manuel",
    "apellido": "Ferraris",
    "email": "ferrarismanu@gmail.com",
    "password": "segura123",
    "telefono": "3411234567",
    "veterinario": {
        "matricula": "VET-002",
        "años_experiencia": "5"
    },
    "adoptante": null,
    "colaborador": null
}

###Registrar un adoptante
POST http://localhost:3000/api/personas
Content-Type: application/json

{
    "dni": 87633,
    "nombre": "Carlos",
    "apellido": "Pérez",
    "email": "caryys@sara.org",
    "contraseña": "clave456",
    "telefono": "3417654321",
    "veterinario": null,
    "adoptante": {
        "estado": "Apto",
        "domicilio": "Calle Falsa 123"
    },
    "colaborador": null
}

###Registrar un Colaborador
POST http://localhost:3000/api/personas
Content-Type: application/json

{
    "dni": 14587125,
    "nombre": "Mariela",
    "apellido": "Gonzalez",
    "email": "mari@sara.org",
    "password": "segura123",
    "telefono": "3411234567",
    "veterinario": null,
    "adoptante": null,
    "colaborador": {
        "id_colaborador": "COL-002"
    }
}

###Actualizar persona por DNI
PUT http://localhost:3000/api/personas/12345678
Content-Type: application/json

{
    "telefono": "3419999999",
    "email": "ana.actualizada@sara.org"
}

###DELETE - Eliminar persona por DNI
DELETE http://localhost:3000/api/personas/34581075
Content-Type: application/json

### Signup de persona adoptante
POST http://localhost:3000/api/personas/signup
Content-Type: application/json

{
    "dni": 34581075,
    "nombre": "Manuel",
    "apellido": "Ferraris",
    "email": "ferrarismanu2@gmail.com",
    "telefono": "3411234567",
    "password": "segura123",
    "estado": "Apto",
    "domicilio": "Calle Falsa 123"
}