###Listar todas las personas
GET http://localhost:3000/api/personas

###Obtener una persona por DNI
GET http://localhost:3000/api/personas/12345678

###Registrar un veterinario
POST http://localhost:3000/api/personas
Content-Type: application/json

{
    "dni": 12345678,
    "nombre": "Ana",
    "apellido": "Gómez",
    "email": "ana@sara.org",
    "password": "segura123",
    "telefono": "3411234567",
    "veterinario": {
        "matricula": "VET-001",
        "años_experiencia": "5"
    },
    "adoptante": null,
    "colaborador": null
}

###Registrar un adoptante
POST http://localhost:3000/api/personas
Content-Type: application/json

{
    "dni": 87633,
    "nombre": "Carlos",
    "apellido": "Pérez",
    "email": "caryys@sara.org",
    "contraseña": "clave456",
    "telefono": "3417654321",
    "veterinario": null,
    "adoptante": {
        "estado": "Apto",
        "domicilio": "Calle Falsa 123"
    },
    "colaborador": null
}

###Registrar un Colaborador
POST http://localhost:3000/api/personas
Content-Type: application/json

{
    "dni": 24456538954,
    "nombre": "Pedro",
    "apellido": "Gómez",
    "email": "pgwdw@sara.org",
    "contraseña": "segura123",
    "telefono": "24778989896",
    "veterinario": null,
    "adoptante": null,
    "colaborador": {
        "id_colaborador": "COL-007"
    }
}

###Actualizar persona por DNI
PUT http://localhost:3000/api/personas/12345678
Content-Type: application/json

{
    "telefono": "3419999999",
    "email": "ana.actualizada@sara.org"
}

###DELETE - Eliminar persona por DNI
DELETE http://localhost:3000/api/personas/14587453
Content-Type: application/json
