### Obtener todas las fichas medicas
GET http://localhost:3000/api/fichasMed

### Obtener una ficha medica por nro
GET http://localhost:3000/api/fichasMed/2

### Registrar una nueva ficha medica
POST http://localhost:3000/api/fichasMed
Content-Type: application/json

{
    "nro_ficha": 2,
    "nro_animal": 1,
    "matricula": "101010",
    "nro_vacunas": [1, 3],
    "observaciones": "Vacunas colocadas",
    "fecha": "10/10/2025"
}

### Actualizar una ficha existente
PUT http://localhost:3000/api/fichasMed/
Content-Type: application/json

{
    "nro_vacunas": [1, 2, 3],
    "observaciones": "Nuevas vacunas colocadas",
    "fecha": "25/10/2025"
}

### Eliminar una ficha existente
DELETE http://localhost:3000/api/fichasMed/